#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql_db
#    links:
#      - mysql_db:blogApp
#  mysql_db:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: blogApp
##      MYSQL_USER: root
##      MYSQL_PASSWORD: Jayjay24u
#      MYSQL_ROOT_PASSWORD: Jayjay24u


version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    command: sh -c './wait-for mysqldb:3306 -- npm start'
  mysqldb:
    image: "mysql:8.0.29"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: blogApp
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Jayjay24u
      MYSQL_ROOT_PASSWORD: root